diffusion:
  type: "base"
  name: "Test_simple"
  path: "./outputs/"
  contigs: "100-100"
  iterations: 50
  num_designs: 1
  noise_scale: 1

validation:
  num_seqs: 5
  initial_guess: False
  num_recycles: 1
  use_multimer: False
  rm_aa: "" # Bias, make aa less likely